define([], function() {
  return {
    "PropertyPaneDescription": "Description",
    "BasicGroupName": "Group Name",
    "LanguageFieldLabel": "Language",
    "DebugFieldLabel": "Debug Mode",
    "CacheTimeLabel": "Cache Time",
    "CacheTimeDescription": "Number of minutes before fetching new data.",
    "AppLocalEnvironmentSharePoint": "The app is running on your local environment as SharePoint web part",
    "AppLocalEnvironmentTeams": "The app is running on your local environment as Microsoft Teams app",
    "AppLocalEnvironmentOffice": "The app is running on your local environment in office.com",
    "AppLocalEnvironmentOutlook": "The app is running on your local environment in Outlook",
    "AppSharePointEnvironment": "The app is running on SharePoint page",
    "AppTeamsTabEnvironment": "The app is running in Microsoft Teams",
    "AppOfficeEnvironment": "The app is running in office.com",
    "AppOutlookEnvironment": "The app is running in Outlook",
    "UnknownEnvironment": "The app is running in an unknown environment",
    "JobTitle": "Job Title",
    "Department": "Department",
    "ClassificationCode": "Classification Code",
    "Level": "Classification Level",
    "LanguageRequirement": "Language Requirement",
    "LanguageComprehension": "Language Comprehension",
    "Location": "City",
    "Duration": "Duration",
    "Clear": "Clear",
    "Search": "Search",
    "AdvancedSearch": "Advanced Search",
    "btnExpanderOpen": "Click to close Advanced Search",
    "btnExpanderClosed": "Click to open Advanced Search",
    "btnClearAria": "Click to clear all your Advanced Search selection options.",
    "btnSearchAria": "Click to begin your advanced search for job opportunities.",
    "operatorLessThan": "Less or equal to",
    "operatorGreaterThan": "Greater or equal to",
    "operatorExactly": "Exactly",
    "durationAmount" : "Duration Amount",
    "durationUnit": "Duration Unit",
    "English": "English",
    "French": "French",
    "Reading": "Reading comprehension",
    "Written": "Written expression",
    "Oral": "Oral expression",
    "ddPlaceholder": "--Choose one--",
    "titlePlaceholder": "--Enter a job title--",
  }
});