define([], function() {
    return {
      "PropertyPaneDescription": "Description",
      "BasicGroupName": "Group Name",
      "LanguageFieldLabel": "Langue",
      "DebugFieldLabel": "Mode débogage",
      "CacheTimeLabel": "Temps de cache",
      "CacheTimeDescription": "Nombre de minutes avant la récupération de nouvelles données.",
      "AppLocalEnvironmentSharePoint": "The app is running on your local environment as SharePoint web part",
      "AppLocalEnvironmentTeams": "The app is running on your local environment as Microsoft Teams app",
      "AppLocalEnvironmentOffice": "The app is running on your local environment in office.com",
      "AppLocalEnvironmentOutlook": "The app is running on your local environment in Outlook",
      "AppSharePointEnvironment": "The app is running on SharePoint page",
      "AppTeamsTabEnvironment": "The app is running in Microsoft Teams",
      "AppOfficeEnvironment": "The app is running in office.com",
      "AppOutlookEnvironment": "The app is running in Outlook",
      "UnknownEnvironment": "The app is running in an unknown environment",
      "JobTitle": "Titre de l'opportunité",
      "Department": "Organisation du GC",
      "ClassificationCode": "Code de classement",
      "Level": "Niveau de classification",
      "LanguageRequirement": "Exigence linguistique",
      "LanguageComprehension": "Compréhension du langage",
      "Location": "Ville",
      "Duration": "Durée",
      "Clear": "Effacer",
      "Search": "Rechercher",
      "AdvancedSearch": "Recherche avancée",
      "btnExpanderOpen": "Cliquez pour fermer la recherche avancée",
      "btnExpanderClosed": "Cliquez pour ouvrir la recherche avancée",
      "btnClearAria": "Cliquez pour effacer toutes vos options de sélection de recherche avancée.",
      "btnSearchAria": "Cliquez pour commencer votre recherche avancée d'opportunités.",
      "operatorLessThan": "Inférieur ou égal à",
      "operatorGreaterThan": "Supérieur ou égal à",
      "operatorExactly": "Exactement",
      "durationAmount" : "Durée montant",
      "durationUnit": "Unité de durée",
      "English": "Anglaise",
      "French": "Français",
      "Reading": "Compréhension écrite",
      "Written": "Expression écrite",
      "Oral": "Expression orale",
      "ddPlaceholder": "--Choisissez-en un--",
      "titlePlaceholder": "--Entrez un titre pour l'opportunité--",
    }
  });
